export interface Entity {
  name: string;
  image: string;
  url: string;
  type: string;
}

export const PLANNER_ENTITIES: Entity[] = [
  {
    name: "Closed Door",
    image: "/bp3d/models/thumbnails/closed_door.png",
    url: "/bp3d/models/gltf/closed_door_28x80.glb",
    type: "InWallFloorEntity",
  },
  {
    name: "Open Door",
    image: "/bp3d/models/thumbnails/open_door.png",
    url: "/bp3d/models/gltf/open_door.glb",
    type: "InWallFloorEntity",
  },
  {
    name: "Door",
    image: "/bp3d/models/thumbnails/door.png",
    url: "/bp3d/models/gltf/door.glb",
    type: "InWallFloorEntity",
  },
  {
    name: "Window",
    image: "/bp3d/models/thumbnails/white_window.png",
    url: "/bp3d/models/gltf/white_window.glb",
    type: "InWallEntity",
  },
  {
    name: "Residential Window",
    image: "/bp3d/models/thumbnails/residential_window.png",
    url: "/bp3d/models/gltf/residential_window.glb",
    type: "InWallEntity",
  },
  {
    name: "Glass Window",
    image: "/bp3d/models/thumbnails/glass_window.png",
    url: "/bp3d/models/gltf/glass_window.glb",
    type: "InWallEntity",
  },
  {
    name: "Glass Window 2",
    image: "/bp3d/models/thumbnails/glass_window2.png",
    url: "/bp3d/models/gltf/glass_window2.glb",
    type: "InWallEntity",
  },
  {
    name: "Shop Window",
    image: "/bp3d/models/thumbnails/shop_window.png",
    url: "/bp3d/models/gltf/shop_window.glb",
    type: "InWallEntity",
  },
  {
    name: "Chair",
    image: "/bp3d/models/thumbnails/chair.jpg",
    url: "/bp3d/models/gltf/chair_oak_white.glb",
    type: "FloorEntity",
  },
  {
    name: "Red Chair",
    image: "/bp3d/models/thumbnails/red_chair.png",
    url: "/bp3d/models/gltf/red_chair.glb",
    type: "FloorEntity",
  },
  {
    name: "Blue Chair",
    image: "/bp3d/models/thumbnails/blue_chair.png",
    url: "/bp3d/models/gltf/blue_chair.glb",
    type: "FloorEntity",
  },
  {
    name: "Office Chair",
    image: "/bp3d/models/thumbnails/office_chair.png",
    url: "/bp3d/models/gltf/office_chair.glb",
    type: "FloorEntity",
  },
  {
    name: "Office Chair 2",
    image: "/bp3d/models/thumbnails/office_chair2.png",
    url: "/bp3d/models/gltf/office_chair2.glb",
    type: "FloorEntity",
  },
  {
    name: "Dresser - Dark Wood",
    image: "/bp3d/models/thumbnails/dresser_dark_wood.png",
    url: "/bp3d/models/gltf/dresser_dark_wood.glb",
    type: "FloorEntity",
  },
  {
    name: "Dresser - White",
    image: "/bp3d/models/thumbnails/dresser_white.jpg",
    url: "/bp3d/models/gltf/dresser_white.glb",
    type: "FloorEntity",
  },
  {
    name: "Bedside table - Shale",
    image: "/bp3d/models/thumbnails/bedside_table_shale.jpg",
    url: "/bp3d/models/gltf/bedside_table_shale.glb",
    type: "FloorEntity",
  },
  {
    name: "Bedside table - White",
    image: "/bp3d/models/thumbnails/bedside_table_shale_white.jpg",
    url: "/bp3d/models/gltf/bedside_table_shale_white.glb",
    type: "FloorEntity",
  },
  {
    name: "Bed",
    image: "/bp3d/models/thumbnails/bed.png",
    url: "/bp3d/models/gltf/bed.glb",
    type: "FloorEntity",
  },
  {
    name: "Full Bed",
    image: "/bp3d/models/thumbnails/full_bed.jpg",
    url: "/bp3d/models/gltf/full_bed.glb",
    type: "FloorEntity",
  },
  {
    name: "Bookshelf",
    image: "/bp3d/models/thumbnails/bookshelf.jpg",
    url: "/bp3d/models/gltf/bookshelf.glb",
    type: "FloorEntity",
  },
  {
    name: "Media Console - White",
    image: "/bp3d/models/thumbnails/media_console_white.jpg",
    url: "/bp3d/models/gltf/media_console_white.glb",
    type: "FloorEntity",
  },
  {
    name: "Sofa - Grey",
    image: "/bp3d/models/thumbnails/sofa_grey.jpg",
    url: "/bp3d/models/gltf/sofa_grey.glb",
    type: "FloorEntity",
  },
  {
    name: "Wooden Trunk",
    image: "/bp3d/models/thumbnails/wooden_trunk.jpg",
    url: "/bp3d/models/gltf/wooden_trunk.glb",
    type: "FloorEntity",
  },
  {
    name: "Floor Lamp",
    image: "/bp3d/models/thumbnails/floor_lamp.png",
    url: "/bp3d/models/gltf/floor_lamp.glb",
    type: "FloorEntity",
  },
  {
    name: "Coffee Table - Wood",
    image: "/bp3d/models/thumbnails/coffee_table_wood.jpg",
    url: "/bp3d/models/gltf/coffee_table_wood.glb",
    type: "FloorEntity",
  },
  {
    name: "Side Table",
    image: "/bp3d/models/thumbnails/side_table.png",
    url: "/bp3d/models/gltf/side_table.glb",
    type: "FloorEntity",
  },
  {
    name: "Dining Table",
    image: "/bp3d/models/thumbnails/dining_table.jpg",
    url: "/bp3d/models/gltf/dining_table.glb",
    type: "FloorEntity",
  },
  {
    name: "Blue Rug",
    image: "/bp3d/models/thumbnails/blue_rug.png",
    url: "/bp3d/models/gltf/blue_rug_60x96.glb",
    type: "FloorEntity",
  },
  {
    name: "NYC Poster",
    image: "/bp3d/models/thumbnails/nyc_poster.jpg",
    url: "/bp3d/models/gltf/nyc_poster2.glb",
    type: "WallEntity",
  },
  {
    name: "Wall Clock",
    image: "/bp3d/models/thumbnails/wall_clock.png",
    url: "/bp3d/models/gltf/wall_clock.glb",
    type: "WallEntity",
  },
  {
    name: "Desk",
    image: "/bp3d/models/thumbnails/desk.png",
    url: "/bp3d/models/gltf/desk.glb",
    type: "FloorEntity",
  },
  {
    name: "Back Brace",
    image: "/bp3d/models/thumbnails/back_brace.png",
    url: "/bp3d/models/gltf/back_brace.gltf",
    type: "FloorEntity",
  },
  {
    name: "Checkstand",
    image: "/bp3d/models/thumbnails/checkstand.png",
    url: "/bp3d/models/gltf/checkstand.gltf",
    type: "FloorEntity",
  },
  {
    name: "Shelve",
    image: "/bp3d/models/thumbnails/shelve.png",
    url: "/bp3d/models/gltf/shelve.gltf",
    type: "FloorEntity",
  },
  {
    name: "Shelve 2",
    image: "/bp3d/models/thumbnails/shelve2.png",
    url: "/bp3d/models/gltf/shelve2.glb",
    type: "FloorEntity",
  },
  {
    name: "Shelve 3",
    image: "/bp3d/models/thumbnails/shelve3.png",
    url: "/bp3d/models/gltf/shelve3.glb",
    type: "FloorEntity",
  },
  {
    name: "Shelf",
    image: "/bp3d/models/thumbnails/shelf.png",
    url: "/bp3d/models/gltf/shelf.glb",
    type: "FloorEntity",
  },
  {
    name: "Shelf 2",
    image: "/bp3d/models/thumbnails/shelf2.png",
    url: "/bp3d/models/gltf/shelf2.glb",
    type: "FloorEntity",
  },
  {
    name: "Shelf 3",
    image: "/bp3d/models/thumbnails/shelf3.png",
    url: "/bp3d/models/gltf/shelf3.glb",
    type: "FloorEntity",
  },
  {
    name: "Glass Window 3",
    image: "/bp3d/models/thumbnails/glass_window3.jpg",
    url: "/bp3d/models/gltf/glass_window3.glb",
    type: "InWallFloorEntity",
  },
  {
    name: "Window 2",
    image: "/bp3d/models/thumbnails/window.png",
    url: "/bp3d/models/gltf/window.glb",
    type: "InWallEntity",
  },
  {
    name: "Door 2",
    image: "/bp3d/models/thumbnails/door2.png",
    url: "/bp3d/models/gltf/door2.glb",
    type: "InWallFloorEntity",
  },
  {
    name: "Storefront",
    image: "/bp3d/models/thumbnails/zhiyin_storefront.png",
    url: "/bp3d/models/gltf/zhiyin_storefront.glb",
    type: "BasicEntity",
  },
  {
    name: "Storefront Text",
    image: "/bp3d/models/thumbnails/zhiyin_storefront_text.png",
    url: "/bp3d/models/gltf/zhiyin_storefront_text.glb",
    type: "BasicEntity",
  },
  {
    name: "Storefront Background",
    image: "/bp3d/models/thumbnails/zhiyin_storefront_background.png",
    url: "/bp3d/models/gltf/zhiyin_storefront_background.glb",
    type: "BasicEntity",
  },
  {
    name: "Small Shelf A",
    image: "/bp3d/models/thumbnails/小货架A.png",
    url: "/bp3d/models/gltf/小货架A.glb",
    type: "FloorEntity",
  },
  {
    name: "Small Shelf B",
    image: "/bp3d/models/thumbnails/小货架B.png",
    url: "/bp3d/models/gltf/小货架B.glb",
    type: "FloorEntity",
  },
  {
    name: "Checkout Counter A",
    image: "/bp3d/models/thumbnails/收银台A.png",
    url: "/bp3d/models/gltf/收银台A.glb",
    type: "FloorEntity",
  },
  {
    name: "Checkout Counter B",
    image: "/bp3d/models/thumbnails/收银台B.png",
    url: "/bp3d/models/gltf/收银台B.glb",
    type: "FloorEntity",
  },
  {
    name: "Checkout Counter C",
    image: "/bp3d/models/thumbnails/收银台C.png",
    url: "/bp3d/models/gltf/收银台C.glb",
    type: "FloorEntity",
  },
];
